spring:
  application:
    name: franchise-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/franchise-db}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8080

app:
  security:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
    jwt:
      secret: ${JWT_SECRET:nequi-franchise-api-super-secret-key-2024}
